<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends EntityRepository
{
    public function get()
    {
        $return = [];
        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:Statistic s'
            )
            ->getOneOrNullResult();
        
        foreach ($result->getTimeProperties() as $property) {
            $value = $result->{'get'. ucfirst($property)}();
            $item = [];
            $item['seconds'] = (int) $value;
            $item['minutes'] = (int) ($value / 60);
            $item['hours'] = (int) ($item['minutes'] / 60);
            $item['days'] = (int) ($item['hours'] / 24);
            $item['months'] = (int) ($item['days'] / 30);
            $item['years'] = (int) ($item['months'] / 12);
            
            $return[$property] = $item;
        }
        
        /*ticketsTotal:
        ticketsLastMonth:
        ticketsUntilLastMonth:
        ticketsThisMonth:*/
        
        $return['ticketsTotal'] = $result->getTicketsTotal();
        $return['ticketsLastMonth'] = $result->getTicketsLastMonth();
        $return['ticketsLastMonthPeriod'] = $result->getTicketsLastMonth();
        $return['ticketsUntilLastMonth'] = $result->getTicketsUntilLastMonth();
        $return['ticketsThisMonth'] = $result->getTicketsThisMonth();
        
        return $return;
    }
}
